// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auction/v1/auction.proto

package auctionv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAuctionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AuctionId         string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	OpeningPriceCents int64                  `protobuf:"varint,2,opt,name=opening_price_cents,json=openingPriceCents,proto3" json:"opening_price_cents,omitempty"`
	DurationSec       int64                  `protobuf:"varint,3,opt,name=duration_sec,json=durationSec,proto3" json:"duration_sec,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateAuctionRequest) Reset() {
	*x = CreateAuctionRequest{}
	mi := &file_auction_v1_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuctionRequest) ProtoMessage() {}

func (x *CreateAuctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_v1_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuctionRequest.ProtoReflect.Descriptor instead.
func (*CreateAuctionRequest) Descriptor() ([]byte, []int) {
	return file_auction_v1_auction_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAuctionRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *CreateAuctionRequest) GetOpeningPriceCents() int64 {
	if x != nil {
		return x.OpeningPriceCents
	}
	return 0
}

func (x *CreateAuctionRequest) GetDurationSec() int64 {
	if x != nil {
		return x.DurationSec
	}
	return 0
}

type PlaceBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionId     string                 `protobuf:"bytes,1,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty"`
	BidId         string                 `protobuf:"bytes,2,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AmountCents   int64                  `protobuf:"varint,4,opt,name=amount_cents,json=amountCents,proto3" json:"amount_cents,omitempty"`
	ClientTsMs    int64                  `protobuf:"varint,5,opt,name=client_ts_ms,json=clientTsMs,proto3" json:"client_ts_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	mi := &file_auction_v1_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auction_v1_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_auction_v1_auction_proto_rawDescGZIP(), []int{1}
}

func (x *PlaceBidRequest) GetAuctionId() string {
	if x != nil {
		return x.AuctionId
	}
	return ""
}

func (x *PlaceBidRequest) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

func (x *PlaceBidRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PlaceBidRequest) GetAmountCents() int64 {
	if x != nil {
		return x.AmountCents
	}
	return 0
}

func (x *PlaceBidRequest) GetClientTsMs() int64 {
	if x != nil {
		return x.ClientTsMs
	}
	return 0
}

type PlaceBidResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Accepted          bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Duplicate         bool                   `protobuf:"varint,2,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	Reason            string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	CurrentPriceCents int64                  `protobuf:"varint,4,opt,name=current_price_cents,json=currentPriceCents,proto3" json:"current_price_cents,omitempty"`
	WinnerUserId      string                 `protobuf:"bytes,5,opt,name=winner_user_id,json=winnerUserId,proto3" json:"winner_user_id,omitempty"`
	Version           int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	EventId           string                 `protobuf:"bytes,7,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	ServerTsMs        int64                  `protobuf:"varint,8,opt,name=server_ts_ms,json=serverTsMs,proto3" json:"server_ts_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *PlaceBidResponse) Reset() {
	*x = PlaceBidResponse{}
	mi := &file_auction_v1_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResponse) ProtoMessage() {}

func (x *PlaceBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auction_v1_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResponse.ProtoReflect.Descriptor instead.
func (*PlaceBidResponse) Descriptor() ([]byte, []int) {
	return file_auction_v1_auction_proto_rawDescGZIP(), []int{2}
}

func (x *PlaceBidResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *PlaceBidResponse) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *PlaceBidResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PlaceBidResponse) GetCurrentPriceCents() int64 {
	if x != nil {
		return x.CurrentPriceCents
	}
	return 0
}

func (x *PlaceBidResponse) GetWinnerUserId() string {
	if x != nil {
		return x.WinnerUserId
	}
	return ""
}

func (x *PlaceBidResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PlaceBidResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *PlaceBidResponse) GetServerTsMs() int64 {
	if x != nil {
		return x.ServerTsMs
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_auction_v1_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_auction_v1_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_auction_v1_auction_proto_rawDescGZIP(), []int{3}
}

var File_auction_v1_auction_proto protoreflect.FileDescriptor

const file_auction_v1_auction_proto_rawDesc = "" +
	"\n" +
	"\x18auction/v1/auction.proto\x12\n" +
	"auction.v1\"\x88\x01\n" +
	"\x14CreateAuctionRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12.\n" +
	"\x13opening_price_cents\x18\x02 \x01(\x03R\x11openingPriceCents\x12!\n" +
	"\fduration_sec\x18\x03 \x01(\x03R\vdurationSec\"\xa5\x01\n" +
	"\x0fPlaceBidRequest\x12\x1d\n" +
	"\n" +
	"auction_id\x18\x01 \x01(\tR\tauctionId\x12\x15\n" +
	"\x06bid_id\x18\x02 \x01(\tR\x05bidId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\famount_cents\x18\x04 \x01(\x03R\vamountCents\x12 \n" +
	"\fclient_ts_ms\x18\x05 \x01(\x03R\n" +
	"clientTsMs\"\x91\x02\n" +
	"\x10PlaceBidResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1c\n" +
	"\tduplicate\x18\x02 \x01(\bR\tduplicate\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12.\n" +
	"\x13current_price_cents\x18\x04 \x01(\x03R\x11currentPriceCents\x12$\n" +
	"\x0ewinner_user_id\x18\x05 \x01(\tR\fwinnerUserId\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x12\x19\n" +
	"\bevent_id\x18\a \x01(\tR\aeventId\x12 \n" +
	"\fserver_ts_ms\x18\b \x01(\x03R\n" +
	"serverTsMs\"\a\n" +
	"\x05Empty2\x9d\x01\n" +
	"\x0eAuctionService\x12D\n" +
	"\rCreateAuction\x12 .auction.v1.CreateAuctionRequest\x1a\x11.auction.v1.Empty\x12E\n" +
	"\bPlaceBid\x12\x1b.auction.v1.PlaceBidRequest\x1a\x1c.auction.v1.PlaceBidResponseBBZ@github.com/Abhi1264/auctioneer/apps/api/gen/auction/v1;auctionv1b\x06proto3"

var (
	file_auction_v1_auction_proto_rawDescOnce sync.Once
	file_auction_v1_auction_proto_rawDescData []byte
)

func file_auction_v1_auction_proto_rawDescGZIP() []byte {
	file_auction_v1_auction_proto_rawDescOnce.Do(func() {
		file_auction_v1_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auction_v1_auction_proto_rawDesc), len(file_auction_v1_auction_proto_rawDesc)))
	})
	return file_auction_v1_auction_proto_rawDescData
}

var file_auction_v1_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_auction_v1_auction_proto_goTypes = []any{
	(*CreateAuctionRequest)(nil), // 0: auction.v1.CreateAuctionRequest
	(*PlaceBidRequest)(nil),      // 1: auction.v1.PlaceBidRequest
	(*PlaceBidResponse)(nil),     // 2: auction.v1.PlaceBidResponse
	(*Empty)(nil),                // 3: auction.v1.Empty
}
var file_auction_v1_auction_proto_depIdxs = []int32{
	0, // 0: auction.v1.AuctionService.CreateAuction:input_type -> auction.v1.CreateAuctionRequest
	1, // 1: auction.v1.AuctionService.PlaceBid:input_type -> auction.v1.PlaceBidRequest
	3, // 2: auction.v1.AuctionService.CreateAuction:output_type -> auction.v1.Empty
	2, // 3: auction.v1.AuctionService.PlaceBid:output_type -> auction.v1.PlaceBidResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auction_v1_auction_proto_init() }
func file_auction_v1_auction_proto_init() {
	if File_auction_v1_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auction_v1_auction_proto_rawDesc), len(file_auction_v1_auction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auction_v1_auction_proto_goTypes,
		DependencyIndexes: file_auction_v1_auction_proto_depIdxs,
		MessageInfos:      file_auction_v1_auction_proto_msgTypes,
	}.Build()
	File_auction_v1_auction_proto = out.File
	file_auction_v1_auction_proto_goTypes = nil
	file_auction_v1_auction_proto_depIdxs = nil
}
